version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Abc123456
      MYSQL_DATABASE: email_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask:
    build: .
    container_name: flask_container
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URI=mysql+mysqlconnector://root:Abc123456@mysql/email_db
    depends_on:
      - mysql

  frontend:
    image: node:16
    container_name: frontend_container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: ["npm", "start"]
    depends_on:
      - flask

volumes:
  mysql_data:
